name: Build and Publish Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Make mvnw executable
        run: chmod +x demoJavaProject/mvnw

      - name: Build with Maven
        run: demoJavaProject/./mvnw clean package
        working-directory: ./demoJavaProject  # Add this line

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: index.docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/demo-java-project:latest

      - name: Image details
        run: |
          echo "Pushed image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/demo-java-project:latest"
          echo "Built with Maven"
