- name: Set up JDK 17
  uses: actions/setup-java@v3
  with:
    java-version: '17'
    distribution: 'temurin'

- name: Make mvnw executable
  run: chmod +x ./mvnw

- name: Build with Maven Wrapper
  run: ./mvnw clean package
  working-directory: ./demoJavaProject
