name: Maven Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      path: ~/.m2/repository
      key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      restore-keys: |
        ${{ runner.os }}-maven-
    - name: Build and Test with Maven
      run: |
        #!/bin/bash
        echo "Starting Maven build and test..."
        mvn clean install -B
        echo "Maven build and test completed."
